services:
  source-gateway:
    image: nginx:alpine
    container_name: source-gateway
    ports:
      - "8081:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
